apiVersion: v1
kind: Pod
metadata:
  name: tomcat
  labels:
    app: tomcat
spec:
  containers:
  - name: tomcat
    image: tomcat:jdk8-openjdk-slim
    ports:
    - containerPort: 80
    - name: jmx
      containerPort: 30100
    volumeMounts:
    - name: workdir
      mountPath: /app
    env: 
    - name: JAVA_TOOL_OPTIONS
      value: "-javaagent:/app/jmx_prometheus_javaagent-0.17.2.jar=30100:/app/config.yml"
  initContainers:
  - name: install
    image: fayfa/jmx:v3
    command:
    - sh
    - "-ce"
    - |
      set -ex
      cp -r /app/* /work-dir/
    volumeMounts:
    - name: workdir
      mountPath: "/work-dir"
  volumes:
  - name: workdir
    emptyDir: {}