apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: tomcat
  name: tomcat
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    name: http
  - port: 30100
    protocol: TCP
    targetPort: 30100
    name: jmx
  selector:
    app: tomcat
status:
  loadBalancer: {}
